#!/bin/bash
reset
clear
echo "Enter Your Number Between 0 to 100 "
read grade

if [ $grade -lt 40 ]
 then
 	echo " |-----------You have been given F grade---------------| "
elif [ $grade -lt 70 -a $grade -ge 40 ]
then 
	echo "|-------------Grade C have be given to you-------------| "
else
	echo "|--------------Invalid Number Please try Again-------------| "
fi
